services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    depends_on:
      - mongo
      - redis

    # env_file: .env

  frontend:
    build: ./frontend
    ports:
      - "5173:80"
    # volumes:
    #   - ./frontend:/app
    # stdin_open: true
    # tty: true
    # depends_on:
    #   - backend
    
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"

  redis:
    image: redis:7
    ports:
      - "6379:6379"